apiVersion: v2
name: registry-server
description: The Apigee Registry API server.

type: application

# The chart version.
version: 0.1.1

# The version number of the application being deployed.
appVersion: "v0.6.10"
