# Default values for registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/apigee/registry-tools
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: main

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

registry:
  host: registry-server.registry.svc.cluster.local
  port: 80
  project: catalog

podAnnotations: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
