apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: viewer
spec:
  tls:
  - hosts:
      - {{ .Values.ingress.host }}
    secretName: grpc-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "registry.fullname" . }}
            port: 
              number: 80
